[theme]
base = "light"
primaryColor = "#5B8DB8"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4FBFC"
textColor = "#203040"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
