[theme]
primaryColor = "#00A087"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1B1F23"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
